//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andeart.JsonButler.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andeart.JsonButler.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Rick Astley&quot;,
        ///  &quot;lines&quot;: [
        ///    &quot;Never gonna give you up&quot;,
        ///    &quot;Never gonna let you down&quot;,
        ///    &quot;Never gonna run around&quot;,
        ///    &quot;And desert you&quot;
        ///  ],
        ///  &quot;winning_number&quot;: 42,
        ///  &quot;nested_type&quot;: {
        ///    &quot;super_nested_type&quot;: {
        ///      &quot;id&quot;: 3.14
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string ButlerCs0 {
            get {
                return ResourceManager.GetString("ButlerCs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Rick Astley&quot;,
        ///  &quot;lines&quot;: [
        ///    &quot;Never gonna give you up&quot;,
        ///    &quot;Never gonna let you down&quot;,
        ///    &quot;Never gonna run around&quot;,
        ///    &quot;And desert you&quot;
        ///  ],
        ///  &quot;winning_number&quot;: 42,
        ///  &quot;nested_type&quot;: {
        ///    &quot;super_nested_type&quot;: {
        ///      &quot;id&quot;: 3.14
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string ButlerJson0 {
            get {
                return ResourceManager.GetString("ButlerJson0", resourceCulture);
            }
        }
    }
}
